version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    # ports:
    #   - '3000:3000'
    environment:
      - REACT_APP_API_PORT=8080
    #   - REACT_APP_API_URL=api
    depends_on:
      - api
    command: npm start
    volumes:
      - ./frontend/src:/usr/app/src
    tty: true
    stdin_open: true

  api:
    build:
      context: ./backend
    # ports:
    #   - '3001:3001'
    environment:
      - PORT=3001
      # - CORS_PORT=8080
      # - CORS_PORT=3000
      # - CORS_URL=frontend
      - MONGO_PORT=27017
      - MONGO_URL=api_mongo
    depends_on:
      - api_mongo
    command: npm run dev
    volumes:
      - ./backend/src:/usr/app/src
    # networks:
    #   - my_network

  api_mongo:
    image: mongo:4.0.20-xenial
    volumes:
      - mongodb_api:/data/db
    # ports:
    #   - '27017:27017'

  nginx_reverse_proxy:
    image: nginx:1.18-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api

volumes:
  mongodb_api:
