version: '3.7'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_PORT=3001
    #   - REACT_APP_API_URL=api
    depends_on: 
      - api
    command: npm start
    volumes:
      - ./frontend/src:/usr/app/src
    tty: true
    stdin_open: true
    # networks:
    #   - my_network

  api:
    build: 
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - CORS_PORT=3000
      # - CORS_URL=frontend
      - MONGO_PORT=27017
      - MONGO_URL=api_mongo
    command: npm run dev
    volumes: 
      - ./backend/src:/usr/app/src
    # networks:
    #   - my_network

  api_mongo:
    image: mongo:4.0.20-xenial
    volumes:
      - mongodb_api:/data/db
    ports:
      - '27017:27017'

volumes: 
  mongodb_api:

# networks:
#   my_network:
#     name: my_network
#     driver: bridge