version: "3.7"

services:
  express:
    build: 
      context: .
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on: 
      - mongodb

  mongodb:
    image: mongo
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge